"""
Fine-tune DistilBERT as a 3-way intent classifier (qna / reminder / weather)
on the synthetic dataset generated by generate_dataset.py.

Saves the trained model + tokenizer to models/intent_classifier/ and writes
held-out test accuracy to data/classifier/eval_results.json.
"""
import json
from pathlib import Path

import numpy as np
import torch
from datasets import Dataset
from sklearn.metrics import accuracy_score, classification_report
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    Trainer,
    TrainingArguments,
)

ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "data" / "classifier"
MODEL_OUT = ROOT / "models" / "intent_classifier"
MODEL_OUT.mkdir(parents=True, exist_ok=True)

BASE_MODEL = "distilbert-base-uncased"
LABELS = ["qna", "reminder", "weather"]
LABEL2ID = {l: i for i, l in enumerate(LABELS)}
ID2LABEL = {i: l for i, l in enumerate(LABELS)}


def load_split(name: str) -> Dataset:
    raw = json.load(open(DATA_DIR / f"{name}.json"))
    texts = [r["text"] for r in raw]
    labels = [LABEL2ID[r["label"]] for r in raw]
    return Dataset.from_dict({"text": texts, "label": labels})


def main():
    device = "mps" if torch.backends.mps.is_available() else "cpu"
    print(f"Using device: {device}")

    train_ds = load_split("train")
    test_ds = load_split("test")

    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)

    def tokenize(batch):
        return tokenizer(batch["text"], truncation=True, max_length=64)

    train_ds = train_ds.map(tokenize, batched=True)
    test_ds = test_ds.map(tokenize, batched=True)

    model = AutoModelForSequenceClassification.from_pretrained(
        BASE_MODEL,
        num_labels=len(LABELS),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )

    collator = DataCollatorWithPadding(tokenizer=tokenizer)

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        return {"accuracy": accuracy_score(labels, preds)}

    args = TrainingArguments(
        output_dir=str(ROOT / "logs" / "classifier_train"),
        eval_strategy="epoch",
        save_strategy="no",
        learning_rate=3e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        num_train_epochs=6,
        weight_decay=0.01,
        logging_steps=10,
        report_to=[],
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=test_ds,
        processing_class=tokenizer,
        data_collator=collator,
        compute_metrics=compute_metrics,
    )

    trainer.train()

    metrics = trainer.evaluate()
    preds = np.argmax(trainer.predict(test_ds).predictions, axis=-1)
    labels = test_ds["label"]
    report = classification_report(
        labels, preds, target_names=LABELS, output_dict=True
    )

    print(f"\nHeld-out test accuracy: {metrics['eval_accuracy']:.4f}")
    print(classification_report(labels, preds, target_names=LABELS))

    trainer.save_model(str(MODEL_OUT))
    tokenizer.save_pretrained(str(MODEL_OUT))

    with open(DATA_DIR / "eval_results.json", "w") as f:
        json.dump(
            {"accuracy": metrics["eval_accuracy"], "report": report},
            f,
            indent=2,
        )

    print(f"\nModel saved to {MODEL_OUT}")


if __name__ == "__main__":
    main()
